# 01 - Out of Sample validation 
## <b> Adrian Vazquez </b>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from scipy.stats import linregress
early_regime = pd.read_csv("../data/processed/early_regime_dataset.csv")
metadata = pd.read_csv("../data/raw/markets_metadata.csv")
metadata = metadata.rename(columns={"id": "market_id"})
df_alpha = pd.read_csv('../data/processed/regime_alpha_dataset.csv')
df_alpha = df_alpha.merge(metadata[["market_id", "endDate"]],on="market_id",how="left")

In [ ]:
df_alpha["endDate"] = pd.to_datetime(df_alpha["endDate"])
df_alpha = df_alpha.sort_values("endDate")
df_alpha[["market_id","endDate"]].head()

   market_id                   endDate
1     249778 2023-04-02 00:00:00+00:00
2     250474 2023-04-26 00:00:00+00:00
0     248594 2023-05-01 00:00:00+00:00
4     251027 2023-05-22 00:00:00+00:00
6     251046 2023-05-28 00:00:00+00:00

In [ ]:
df_alpha[["market_id","endDate"]].tail()

    market_id                   endDate
30     254573 2024-12-30 12:00:00+00:00
29     254572 2024-12-30 12:00:00+00:00
34     254579 2024-12-30 12:00:00+00:00
33     254578 2024-12-30 12:00:00+00:00
28     254571 2024-12-31 00:00:00+00:00

In [11]:
df_25 = early_regime[early_regime["horizon"] == 0.25]
df_25 = df_25.merge( df_alpha[["market_id", "endDate"]],on="market_id",how="left")

In [12]:
df_25.shape

(43, 34)

In [13]:
df_25["endDate"] = pd.to_datetime(df_25["endDate"])
df_25 = df_25.sort_values("endDate").reset_index(drop=True)
df_25[["market_id","endDate"]].head()

   market_id                   endDate
0     249778 2023-04-02 00:00:00+00:00
1     250474 2023-04-26 00:00:00+00:00
2     248594 2023-05-01 00:00:00+00:00
3     251027 2023-05-22 00:00:00+00:00
4     251046 2023-05-28 00:00:00+00:00

In [14]:
df_25[["market_id","endDate"]].tail()

    market_id                   endDate
38     254573 2024-12-30 12:00:00+00:00
39     254572 2024-12-30 12:00:00+00:00
40     254579 2024-12-30 12:00:00+00:00
41     254578 2024-12-30 12:00:00+00:00
42     254571 2024-12-31 00:00:00+00:00

In [ ]:
split_idx = int(len(df_25) * 0.70)

train_df = df_25.iloc[:split_idx].copy()
test_df = df_25.iloc[split_idx:].copy()

print("Train:", train_df.shape)
print("Test :", test_df.shape)